# -*- coding: utf-8 -*-
"""Copy of Crawl data twitter > 2000 tweets - 30 Maret 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kC6wZAbzejAXTQjpUf3MFO8CT3mO5hKY

# Crawl Data Twitter > 2000 Tweets
The crawling process was done using Tweet-Harvest. Written by Helmi Satria on  March 30th 2024.
"""

#@title Twitter Auth Token

twitter_auth_token = '86b2ad56f4445f2bf29f6453bb6f709803761e46'

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=21 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data

filename = 'gibran.csv'
search_keyword = '(from:MoniPalaciosZ OR from:SixtoParraTovar OR from:PattyMendozaJ OR from:MG_MOLINAM OR from:karinasubiad OR from:GustavoMateusA OR from:GisseGarzonM OR from:JuanPabloMolina OR from:JorgeGuevaraEC OR from:dallyanapass OR from:KatiuskaMEc OR from:mieles_bolivar OR from:SofiaEspinRC OR from:Lucia_Jaramillo OR from:johaortizv OR from:OttoVeraSE OR from:RafaelDavilaE) since:2024-01-17 until:2024-02-17'
limit = 5000

!npx -y tweet-harvest@2.6.0 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

!  pip install tweeterpy

from tweeterpy import TweeterPy
from tweeterpy.util import find_nested_key

twitter = TweeterPy()

# get tweets or other data
user_tweets = twitter.get_user_tweets("elonmusk",total=50)

logged_in()

